/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "washed-purple/washed-purple-50": "#f8f7ff",
        "washed-purple/washed-purple-100": "#e8e7fe",
        "washed-purple/washed-purple-200": "#dddcfd",
        "washed-purple/washed-purple-300": "#cdcbfc",
        "washed-purple/washed-purple-400": "#c4c1fc",
        "washed-purple/washed-purple-500": "#b5b2fb",
        "washed-purple/washed-purple-600": "#a5a2e4",
        "washed-purple/washed-purple-700": "#817eb2",
        "washed-purple/washed-purple-800": "#64628a",
        "washed-purple/washed-purple-900": "#4c4b69",
        "Primary-Purple/primary-purple-50": "#f0e8fe",
        "Primary-Purple/primary-purple-100": "#d0b7fd",
        "Primary-Purple/primary-purple-200": "#ba94fc",
        "Primary-Purple/primary-purple-300": "#9a63fa",
        "Primary-Purple/primary-purple-400": "#8645f9",
        "Primary-Purple/primary-purple-500": "#6816f8",
        "Primary-Purple/primary-purple-600": "#5f14e2",
        "Primary-Purple/primary-purple-700": "#4a10b0",
        "Primary-Purple/primary-purple-800": "#390c88",
        "Primary-Purple/primary-purple-900": "#2c0968",
        "Washed-Blue/washed-blue-50": "#f1f3fe",
        "Washed-Blue/washed-blue-100": "#d3dafd",
        "Washed-Blue/washed-blue-200": "#bec8fc",
        "Washed-Blue/washed-blue-300": "#a1affb",
        "Washed-Blue/washed-blue-400": "#8ea0fa",
        "Washed-Blue/washed-blue-500": "#7288f9",
        "Washed-Blue/washed-blue-600": "#687ce3",
        "Washed-Blue/washed-blue-700": "#5161b1",
        "Washed-Blue/washed-blue-800": "#3f4b89",
        "Washed-Blue/washed-blue-900": "#303969",
        "Primary-Blue/primary-blue-50": "#ebf0fe",
        "Primary-Blue/primary-blue-100": "#c1d0fd",
        "Primary-Blue/primary-blue-200": "#a3b9fc",
        "Primary-Blue/primary-blue-300": "#7898fb",
        "Primary-Blue/primary-blue-400": "#5e85fa",
        "Primary-Blue/primary-blue-500": "#3666f9",
        "Primary-Blue/primary-blue-600": "#315de3",
        "Primary-Blue/primary-blue-700": "#2648b1",
        "Primary-Blue/primary-blue-800": "#1e3889",
        "Primary-Blue/primary-blue-900": "#172b69",
        "Neutrals/neutrals-1": "#ffffff",
        "Neutrals/neutrals-2": "#fcfcfd",
        "Neutrals/neutrals-3": "#f5f5f6",
        "Neutrals/neutrals-4": "#f0f0f1",
        "Neutrals/neutrals-5": "#d9d9dc",
        "Neutrals/neutrals-6": "#c0bfc4",
        "Neutrals/neutrals-7": "#8e8c95",
        "Neutrals/neutrals-8": "#5b5966",
        "Neutrals/neutrals-9": "#474553",
        "Neutrals/neutrals-10": "#292636",
        "Neutrals/neutrals-11": "#211f2f",
        "Neutrals/neutrals-12": "#171426",
        "Neutrals/neutrals-13": "#030013",
        "brand/brand-washedPurple": "#b5b2ff",
        "brand/brand-washedBlue": "#6889ff",
        "brand/brand-primaryBlue": "#0469ff",
        "brand/brand-primaryPurple": "#7000ff",
        "brand/brand-dark": "#030014",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
